ALTER TABLE task_outbox
ADD COLUMN IF NOT EXISTS status SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
ADD COLUMN IF NOT EXISTS last_error TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW ();

CREATE INDEX IF NOT EXISTS idx_task_outbox_pending_next_retry ON task_outbox (status, next_retry_at, id);