database:
  host: "192.168.31.199"
  require_ssl: false

application:
  host: "0.0.0.0"
  base_url: "http://0.0.0.0"

log:
  log_level: "debug"

jwt:
  expiration: 86400 # seconds

storage:
  endpoint: "http://10.41.94.104:9000"
  access_key: "root"
  secret_key: "admin123"
  sig_exp_seconds: 1800 # 30 minutes 
  view_exp_seconds: 86400 # 24 hours

redis:
  uri: "redis://:admin123@192.168.31.199:6379/1"
